### ISSUE TITLE
Should we rename the repository to "elixirschool"?

### ISSUE THREAD

**Issue by eksperimental** [elixirschool/elixirschool#1117]
After submitting this PR: https://github.com/doomspork/elixir-school/pull/1116
I saw that originally the project was named "elixir_school", or at least https://github.com/doomspork/elixir_school redirects to https://github.com/doomspork/elixir-school for some reason.
the thing is that I find annoying every time i have to access the repo, I type elixirschool beacuse that's the name of the website. Should we unify the names and call the repo "elixirschool"?

**Comment by doomspork** [comment]
I don't _really_ have a strong feeling.  I originally went with `elixir-school` because it's `elixir-lang` and I wanted to remain consistent (hence the `_` -> `-` change).

I'm currently working with a designer on a complete overhaul of the Elixir School site and brand, vastly improving the content display, search-ability, and allowing me to tackle a few other goals I have like calling more attention to contributors.  As part of that design work I'm planning to tackle some new lessons and look at standing up a blog for content that falls outside the scope of our lessons.  I'm also leaning towards is moving the project to an org at which time I'm happy to use `ElixirSchool`.

**Comment by eksperimental** [comment]
great move. thank you
