### ISSUE TITLE
Content is *Great* Grammar Can Be Improved in "Advanced > Specifications and Types" lesson

### ISSUE THREAD

**Issue by nelsonic** [elixirschool/elixirschool#1133]
Hi @doomspork, thanks _again_ for the superb learning resource! 🎉 

Would anyone be offended if I submit a PR improving the grammar & punctuation of the "Advanced > Specifications and Types" lesson?

https://elixirschool.com/en/lessons/advanced/typespec/#introduction
![image](https://user-images.githubusercontent.com/194400/28280759-b0795768-6b1c-11e7-98d1-be6213d4a3c6.png)
Snapshot: https://github.com/doomspork/elixir-school/blob/43f37555a7db161c86b5debbbbe5cfd7a170060e/en/lessons/advanced/typespec.md

> _**Note**: the **content** is **great**; @eksperimental is **clearly technically brilliant**! ⭐️ 
however it **appears** that it was written by someone whose **first language** is **not English** ... I'm happy to update the grammar in the lesson and submit a PR for review_. 💭

**Comment by doomspork** [comment]
@nelsonic thanks and welcome!  Please do contribute anywhere you think you could make improvements.  This resource is so great because of contributors like yourself who continuously add value.

I often joke that my first language is Elixir and not English so grammar could likely be improved in many places. 😆
