### ISSUE TITLE
Add Enum.filter to Basic Enum Page

### ISSUE THREAD

**Issue by wilbertliu** [elixirschool/elixirschool#1342]
Hello folks 👋🏻,

Elixir School has been my go-to resource when I need to find something that I might be forgotten. Recently I wonder if there's a `filter` function on Enum and want to find its usage. After I went to the Basic Enum Page, I'm surprized because there's no `Enum.filter` section in it. That made me try to Google it because I'm not sure Elixir doesn't have such function, and found it afterwards.

I believe it might not only me that need such section to learn / recall.
Do we mind to add the `Enum.filter` section? I would be more than happy to contribute. 🙂

**Comment by ybur-yug2** [comment]
@wilbertliu good eye! [We have a contributing guide here](https://github.com/elixirschool/elixirschool/blob/master/CONTRIBUTING.md) and if you can get up and running PRs with improvements are welcome! I personally think its absolutely fitting and would be a good addition.

PS I'm actually @ybur-yug  and am currently just locked out of that account because of an email snafu :P

**Comment by doomspork** [comment]
@wilbertliu please do open a PR 👍 

We're always happy to have community help in enhancing the resource 😁

**Comment by wilbertliu** [comment]
@ybur-yug2 Thanks for pointing that out. Will review the contributing guide then! 😀
@doomspork Sure thing Sean! Will seek a good time to do this. Thanks a lot!
