### ISSUE TITLE
Code formatting for sigils not working

### ISSUE THREAD

**Issue by chadoh** [elixirschool/elixirschool#1355]
On [the Sigils lesson](https://elixirschool.com/en/lessons/basics/sigils/):

<img width="749" alt="broken sigils color formatting" src="https://user-images.githubusercontent.com/221614/37657783-4ef042be-2c22-11e8-8363-4eddb6e129b4.png">

For code newbies, that formatting is going to make their eyes look in all the wrong places.

How complex is fixing this? Can I help?

**Comment by nscyclone** [comment]
Hi, @chadoh, thanks for pointing that out!
We use [`rouge`](https://github.com/elixirschool/elixirschool/blob/master/_config.yml#L27) as a highlighter. It seems like several gems we use are [a little outdated](https://github.com/elixirschool/elixirschool/blob/master/Gemfile.lock#L20-L30). Jekyll allows to [use `rouge 2.0` since 3.6.0](https://github.com/jekyll/jekyll/releases/tag/v3.6.0).

<details>
<summary>I've updated dependencies locally and this part now looks like this:</summary>

![Char List](https://user-images.githubusercontent.com/5345029/37659831-03ed4db2-2c62-11e8-898a-782968482a34.png)

</details>




Probably it's just a good moment for update?
/cc @doomspork @elixirschool/developers

**Comment by doomspork** [comment]
@nscyclone I'm all for bumping the dependencies if it doesn't break anything 👍
