### ISSUE TITLE
en/basics/iex-helpers: `s` not working as advertised

### ISSUE THREAD

**Issue by chadoh** [elixirschool/elixirschool#1358]
The [lesson](https://elixirschool.com/en/lessons/basics/iex-helpers/#s):

```
iex> s Map.merge/2
@spec merge(map(), map()) :: map()
```

IRL:
```
iex> s Map.merge/2
** (CompileError) iex:9: undefined function s/1
```

**Comment by nscyclone** [comment]
Hi, @chadoh, thanks for reporting that!
Since release [1.6.0](https://github.com/elixir-lang/elixir/releases/tag/v1.6.0) information about type specifications for functions and macros is provided by `h`, `s` has been removed. The lesson should be updated accordingly. Would you like to take care about it?

**Comment by chadoh** [comment]
Yes, I can take care of it!
