### ISSUE TITLE
Improve Elixir School front contrast

### ISSUE THREAD

**Issue by TrailingDots** [elixirschool/elixirschool#1429]
While I am interested in reading Elixir School material, I find that reading
this material for a period of time invites eye strain.

As a software professional, I spend more than 8 hours per day reading
computer screens. I like my career choice a lot and want to improve my
internal worth of software by expanding and building upon my Elixir
skills.

However, the gray fonts in Elixir School need to be more readable.
Hopefully this change is not much more than a simple CSS edit.

Web pages are meant to be read, not just to look pretty! And Elixir School
in particular must be easy to read.

Please visit [While I am interested in reading Elixir School material, 
I find that reading this material for a period of time invites eye strain.

As a software professional, I spend more than 8 hours per day reading
computer screens. I like my career choice a lot and want to improve my
internal worth of software by expanding and building upon my Elixir
skills.

However, the medium gray fonts in Elixir School need to be more readable.
Hopefully this change is not much more than a simple CSS edit.

Web pages are meant to be read, not just to look pretty! An Elixir School
in particular must be easy to read.

Please visit [Contrast Rebellion](http://contrastrebellion.com/) for information relating to
low-contrast font colors and the problems this causes.

**Comment by doomspork** [comment]
Hi @TrailingDots 

We love to get feedback from Elixir School users.  One of the reasons folks have found Elixir School to be enjoyable and useful is because it's a product of many people's efforts, much like the new site design.  While I understand your sentiment that it isn’t intended to be pretty, the individual contributors have asked for a more professional and cleaner site for some time to better reflect their translation efforts.  We were fortune enough to have another contributor step up to the plate and offer to make the site changes.

You clearly feel very strongly about this so I would invite you to take the initiative to do something about it and contribute improvements!

Thanks!

**Comment by doomspork** [comment]
@TrailingDots I've gone ahead and assigned this particular issue to you so you get first dibs!  Feel free to ping me when you've got a PR ready and we're get it reviewed ASAP.

Thanks again for getting involved!

**Comment by andersoncardoso** [comment]
I agree, the light gray fonts are hard to see.  
For me to be able to read I have to edit the css, on the dev console, to 
```
body { color: #333; }
```
anyway, thanks for this project. Awesome job :+1: 

### original
![elixirschool_light](https://user-images.githubusercontent.com/597026/42414791-c7a3d09e-8213-11e8-8faf-9a13efc6d403.png)

### contrast
![elixirschool_contrast](https://user-images.githubusercontent.com/597026/42414792-c7cc1a40-8213-11e8-9cf3-0d0b7ccdd55e.png)

**Comment by doomspork** [comment]
@andersoncardoso this is great, would you care to open a PR?

**Comment by nscyclone** [comment]
Seems to be fixed in #1469. Thanks once again, @TrailingDots and @andersoncardoso!
