### ISSUE TITLE
Last commit does not run properly on production

### ISSUE THREAD

**Issue by gemantzu** [elixirschool/elixirschool#1479]
It seems like the git command does not run at all. Thoughts?

**Comment by doomspork** [comment]
@gemantzu I will try to take a peek at this this week, but it may have to do with how Heroku clones the project.

ping @elixirschool/developers

**Comment by gemantzu** [comment]
Oh the app is hosted on heroku? Idk if it is possible to work then... Does the dyno have git installed? Because it might be that the application is not available for the command to run.

**Comment by doomspork** [comment]
@burden think we could get Elixir School setup on a DO box w/ auto deploy?

**Comment by burden** [comment]
Fail. I'm just noticing this thread. If I may inquire, what prompted this issue? It seems to be deploying now. Was the issue solved @gemantzu / @doomspork? 

RE: DigitalOcean, we could throw money at them, but we could also use Github Pages since we're probably gonna have to setup CI anyways. I can work towards that, if this is still a concern. LMK.

**Comment by doomspork** [comment]
@burden it deploys but this feature does not work.  I believe Heroku does a clean `git pull` and doesn't clone the entire history.  As such, this feature doesn't actually work as @gemantzu had intended.

**Comment by doomspork** [comment]
@gemantzu / @burden — for now should we disable this functionality in production but leave the code in the codebase?

**Comment by gemantzu** [comment]
Yeah, it is better this way so that ppl don't get confused by it.

**Comment by doomspork** [comment]
I'm going to close this as it's been a number of years and we're not going to fix this.
