### ISSUE TITLE
German Translations

### ISSUE THREAD

**Issue by pjhampton** [elixirschool/elixirschool#200]
## Get Involved!

We are seeking **German** translators for this project. If you would like to get involved with translating a lesson. Please folk the project and start translating.
- **Set up**
  - [ ] ~~_config.yml~~ /data/locales/de.yml
  - [ ] /data/interlang.yml
  - [ ] index.md 
- **Basics**
  - [ ] Collections
  - [ ] Enum
  - [ ] Pattern Matching
  - [ ] Control Structures
  - [ ] Pipe Operator
  - [ ] Functions
  - [ ] Modules
  - [ ] Mix
  - [ ] Sigils
  - [ ] Documentation
  - [ ] Testing
  - [ ] Custom Mix Tasks
- **Advanced**
  - [ ] concurrency.md
  - [ ] errors.md
  - [ ] erlang.md
  - [ ] escripts.md
  - [ ] otp-concurrency.md
  - [ ] otp-supervisors.md
  - [ ] metaprogramming.md
- **Specifics**
  - [ ]  ecto.md
  - [ ]  eex.md
  - [ ]  ets.md
  - [ ]  mnesia.md
  - [ ]  plug.md

**Note**
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 [Pull Request](https://help.github.com/articles/using-pull-requests/) per lesson.

**Comment by TypedLambda** [comment]
I'll start translation tomorrow as part of a project promoting elixir in germany.

**Comment by pjhampton** [comment]
Thank you so much @TypedLambda

**Comment by TypedLambda** [comment]
First steps are in the [german-translation](https://github.com/TypedLambda/elixir-school/tree/german-translation) branch of my fork.
I submit pull request as soon as i have some additional parts translated, in order to keep the language consistent.
Writing my native language in a technical context is funny. I'm totally not used to write documentation in german.  :smile:

**Comment by doomspork** [comment]
Thank you for the help @TypedLambda

**Comment by stosorio** [comment]
Hi!
I'd like to help out with the german version :)

**Comment by doomspork** [comment]
Any help is more than welcomed @stosorio!

**Comment by TypedLambda** [comment]
Help would be great. I could not find the time getting back to translating yet.
I found it especially hard which jargon to translate and which to keep.
(Translate "collection" or just keep it, Translate "enumeration" or keep it because of the "Enum" module etc. )
I realized that I've not read a computer science or programming language book in German for at least ten years...
if you compile a list of concepts to translate/keep ill might start my effort again ;)
The initial effort is still committed to my repository. Feel free to continue or start over :)

**Comment by Lechindianer** [comment]
I already said it on Twitter but I make efforts to translate it into German. These lessons are already finished: https://github.com/Lechindianer/elixir-school/tree/master/de/lessons

**Comment by ybur-yug** [comment]
@Lechindianer @pjhampton would it make sense to make a `German Translations (master card)` that we could put in the projects board, and create issues for each remaining lesson in german and track it on the master card with a checklist/PR number?

Not sure what the best way is, just wanna make it as easy as possible for new contributors etc.

**Comment by Lechindianer** [comment]
@ybur-yug By the end of the week you should see a PR for all basic lessons. Personally I don't think creating issues for remaining lessons makes sense. You have to update this information manually which is as useful as outdated code comments. It would be more helpful if there was a notification to some kind of sub-groups (translation units) if there's a change on the original English version that says "lession X has changed, please update it to the most recent version!" @doomspork

**Comment by ybur-yug** [comment]
You're the one contributing so if that works for you, I am perfectly fine with it! Just was a thought in general. If you're doing it all in one sweet thats much more effective. With other languages like Portugese theres a lot more people passing things around so it makes more sense on things like that.

Thank you a ton! Looking forward to seeing it :)

**Comment by Lechindianer** [comment]
Can you assign this issue to me? Currently I'm translating the advanced lessons :)

**Comment by ybur-yug** [comment]
@Lechindianer is wont let me assign you, but I will add this to the projects page and get it updated properly. Thanks for all your hard work! Maybe @doomspork could fix the permissions stuff so it could be assigned? Not sure why it wont let me (never have used that feature)

**Comment by optikfluffel** [comment]
Any updated on this? 😸
