### ISSUE TITLE
Korean Translations

### ISSUE THREAD

**Issue by pjhampton** [elixirschool/elixirschool#201]
## Get Involved!

We are seeking **Korean** translators for this project. If you would like to get involved with translating a lesson. Please folk the project and start translating.
- **Set up**
  - [x] _config.yml
  - [x] index.md 
- **Basics**
  - [x] Basics (@devleoper)
  - [x] Collections (@Dalgona)
  - [x] Enum (@malkoG)
  - [x] Pattern Matching (@Dalgona)
  - [x] Control Structures (@Dalgona)
  - [x] Pipe Operator (@Dalgona)
  - [x] Functions (@malkoG)
  - [x] Composition (@devleoper)
  - [x] Mix (@devleoper)
  - [x] Sigils (@Dalgona)
  - [x] Documentation (@malkoG)
  - [x] Testing (@devleoper)
  - [x] Comprehensions (@Dalgona)
  - [x] Strings (@malkoG)
  - [x] Custom Mix Tasks (@Dalgona)
- **Advanced**
  - [x] Erlang Interoperability (@Dalgona)
  - [x] Error Handling (@malkoG)
  - [x] Executables (@devleoper)
  - [x] Concurrency (@malkoG)
  - [x] OTP Concurrency (@malkoG)
  - [x] OTP Supervisors (@riseshia)
  - [x] Metaprogramming (@riseshia)
  - [x] Umbrella Projects (@devleoper)
  - [x] Specifications and types (@devleoper)
- **Specifics**
  - [x] Plug (@riseshia)
  - [x] Ecto (@riseshia)
  - [x] Embedded Elixir (EEx) (@riseshia)
  - [x] Erlang Term Storage (ETS) (@riseshia)
  - [x] Mnesia (@riseshia)

**Note**
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 [Pull Request](https://help.github.com/articles/using-pull-requests/) per lesson.

**Comment by doomspork** [comment]
@Dalgona / @devleoper / @rijgndqw012 — which of these are complete?

**Comment by devleoper** [comment]
@Dalgona, @rijgndqw012 and I made a [Trello board](https://trello.com/b/mDGHoOM2/translation) to track processes of translation work and glossaries. It will be nice to take a look if interested in translations.

**Comment by doomspork** [comment]
@devleoper would you like to be added as a project collaborator so you can manage this Issue and the KO PRs?

**Comment by devleoper** [comment]
@doomspork Sure! I'd love to do this. :laughing:

**Comment by doomspork** [comment]
@devleoper you've been added!  Please refrain from pushes directly to master 👍

**Comment by riseshia** [comment]
Hi, I want to join this issue, however, there is too less information to check which document is translating or not...
Could i assume these is no progress either no pr or completed on todo list?

**Comment by devleoper** [comment]
@riseshia There is [a trellio board](https://trello.com/b/mDGHoOM2/translation) for tracking which documents are in progress or translated.

**Comment by riseshia** [comment]
@devleoper oh, thanks to notice me 👍

**Comment by devleoper** [comment]
@Dalgona @riseshia @rijgndqw012 
I'm going to merge PRs when all of the Basic lessons are traslated (and reviewed). After that, Korean translation PRs will be merged seperately.
Korean: 기본 레슨(`ko/lessons/basics/`)이 얼마 남지 않았으니까 열려 있는 PR은 기본 레슨을 전부 번역하고 나서 적용할까 싶어요. 그 이후에 들어오는 PR은 개별적으로 검토를 거치고 나서 머지할까 합니다!

**Comment by devleoper** [comment]
@Dalgona @riseshia @rijgndqw012
Translating basic lessons are almost done, and all of they are in review or merged! :tada: For peer-reviewing the HTML rendered result(in case of markup errors or some error), I've built [staging environment](http://elixir-school-ko-staging.herokuapp.com/ko/) which has merged all of PRs for basic lesson. If you found something uncomfortable—that means it's able to be greater— in translation while reading this staging, you can give feedback. (You can find PRs easily because all of them are mentioning this issue)
I'm starting to look into it this weekend and I'll merge all of Korean Bacis PRs when we're happy. (and PRs after basic lessons will be merged seperately; unlike this basic-lesson-staging-stuff™.)

Korean: 기초 챕터 한국어 번역이 다 끝나가요, 이미 머지된 변경 사항이거나 아니면 리뷰에 올려졌을 거예요. :tada: 혹시나 일괄적으로 머지를 하면서 HTML 렌더링이 잘못되거나 여태껏 발견하지 못한 문제가 있을 경우를 대비해, 지금 올라와 있는 기본 레슨 풀리퀘의 가장 최신 버전을 전부 머지한 [스테이징 환경](http://elixir-school-ko-staging.herokuapp.com/ko/)을 구축해 보았어요. 레슨을 찬찬히 읽어보면서 조금 더 멋질 가능성이 있는 부분에 대해서는, 얼마든지 피드백을 주실 수 있습니다. (한국어 관련해서 올라온 모든 풀리퀘스트는 이 이슈를 언급하고 있으니, 이 페이지 안에서 쉽게 해당 풀리퀘를 찾으실 수 있을 거예요.)
저는 이번 주말동안 살펴볼까 합니다. 한국어 번역에 참여하시는 분들이 이것을 보고 기쁠 때 현재 올라와 있는 기본 수업들을 머지하도록 할게요. (이후의 수업은 이런 기본-수업-한꺼번에-스테이징-뭐시뭐시™처럼 하지 않고, 개별적으로 머지하겠습니다! 한번에 머지하려니 일이 너무 커질 것 같아서 스테이징 환경을 꾸린 거예요.)

**Comment by riseshia** [comment]
@devleoper  when i find wrong typo from released lession?

**Comment by devleoper** [comment]
@riseshia You can create a new pull request which can fix the typo. Or ask other person(usually the person who made typo) to make a PR.

KO: 수정 사항을 반영하셔서 새로 풀 리퀘스트를 남겨주셔도 되고요, 오자를 내신 분이 직접 수정하시도록 연락하셔서 그 사람이 풀리퀘를 만들도록 하는 것도 좋겠어요.

**Comment by devleoper** [comment]
I mentioned that everybody had their own styles while translating this document in Korean. and Now I'd like to unify the style in translated lessons, and make a guidelines to translate further chapters. (It seems quite late) I've found some differences(to discuss) through our translation:

번역된 한국어 문서에서 번역하신 분 마다 스타일이 다른 점은 이전에도 언급한 적이 있습니다. 이제 기초 레슨을 검토하면서 이런 부분을 통일하고, 다음 챕터를 번역할 때도 이런 부분을 적용해서 통일성이 있게 옮겨오고 싶은데요. (늦은 감이 없지 않아 있지만요.) 지금까지 찾아본 (토론을 해 볼) 차이점은 아래와 같습니다.

 * Using a colon. (콜론 사용하기)

   Some translated versions uses period instead of colons, because colons are seldom used in Korean documentations and it can be changed to more fluent ways. but this needs lots of efforts and it may slightly change the original text.
  일부 번역본에서는 한국어 문서에서 일반적으로 콜론이 사용되지 않기 때문에, 조금 더 앞뒤로 말을 풀어 쓰는 방법을 채택하여 콜론 대신 마침표를 사용하기도 합니다. 하지만 이런 경우에는 많은 노력이 필요할 뿐더러, 원문에서 부가적으로 의미가 더해지거나 빠질 수 있습니다.

 * _italic_ type (_이탤릭체_)

  Italic type is also seldom used in Korean because Lots of Korean fonts doesn't have Italic type (and some systems doesn't apply italic if the font doesn't have type for them). This may cause more efforts to find the meaning of original text and replacing to the proper one.
  대부분의 한국어 폰트에서는 이탤릭체가 지원되지 않고 일부 시스템의 경우 이탤릭체가 없을 경우 일반 글씨로 렌더링하기 때문에, 대부분의 한국어 문서에서는 이탤릭체를 보통 사용하지 않습니다. 하지만 원문에서 이탤릭체로 표기된 부분을 모두 의도를 파악해 적절한 의미를 가진 다른 것들로 대체하기에는 많은 노력이 필요하겠지요.

I think we can bring much efforts to make more friendly text. Any ideas or new topics to discuss? Feel free to express your opinion. (You may write in Korean while discussing if you use Korean in more fluent way.) :rocket: 
저는 조금 더 수고를 하더라도 더 부드럽게 읽힐 수 있는 쪽으로 생각하고 있어요. 다른 생각이 있거나 이야기해 볼 주제가 있으시다면 편안하게 말씀해 주세요. (영어로만 이야기하는 것보다는 한국어로 더 많이 이야기하실 수 있다면 한국어로 쓰셔도 괜찮을 거예요!) :rocket:

**Comment by devleoper** [comment]
Since some participants are studying at the school, they're ~~suffering from~~ preparing the final exam these days. Korean Translations are almost done thanks to great contributions. (this is not the end. I know, Elixir school continues changing and evolving, So does Korean translation.) We can finalize this after the students finish their semester.

Prepare for the final exam of this semester, and take a break when you have a time with elixir. See you at the end of the exam!

**Comment by devleoper** [comment]
@riseshia @malkoG @Dalgona 

There was tons of personal things these days, I apologize for the late responses and to disappoint you. 😞

I've just merged **Basics** and **Specifics** lessons, which has quite enough feedback to launch. and commented about some technical issues (like branch managing or Jekyll-syntax problems). and I started working and giving feedback. :rocket:

Plus while merging PRs, I added your `@username`s to the top of this page each line. I wish these changes make you happy. Some potential issue-related chapters will give credits to translators when the issue had solved. :tada:

**Comment by devleoper** [comment]
Almost there! We have just a few things to complete up-to-date translation! :tada:

* **If you made pull requests currently opened:** Could you handle something that is currently in issues? Checking out and adding just few commits can make PRs merge-ready!
* **If your pull requests are all merged:** Could you review and look for something awkward/need to be modified?

Sometimes Github sends a lot of emails about things and stuffs so frequently, therefore it's hard to focus something on it, I know. but Shall we put on a last spurt? We have just few steps to goal!

@Dalgona, @malkoG, @riseshia

**Comment by Dalgona** [comment]
Finally 30 out of 30! :tada:

**Comment by doomspork** [comment]
This is amazing @devleoper @riseshia @malkoG @Dalgona!!  Thank you so much!

I'd like to tweet something about this, could you please provide me with your twitter handles?

**Comment by riseshia** [comment]
I don't care, mine is @Re_Shia :)

**Comment by Dalgona** [comment]
@doomspork of course! mine is [at]d57pub_

**Comment by devleoper** [comment]
same as my github handle, @devleoper!

**Comment by doomspork** [comment]
Tweeted!  Thank you again for all of your hard work 👍 

https://twitter.com/elixirschool/status/754414448517996544

**Comment by nscyclone** [comment]
Thanks for all your great work! 
You guys were the first to finish the translation race, probably you want to keep the leadership with the freshest [lesson](https://github.com/doomspork/elixir-school/blob/master/lessons/advanced/typespec.md)?

**Comment by Dalgona** [comment]
@nscyclone Of course! Actually @devleoper is already working on it 👍

**Comment by marocchino** [comment]
Waiting for Specifications and types. Any progress?
Can I take it?

**Comment by Dalgona** [comment]
Let's give him some more time :)

**Comment by marocchino** [comment]
🙆

**Comment by devleoper** [comment]
Currently I'm working on this...but there are lots of thing that I have to care about. I'll try to finish this until this weekend. I apologize.

One more suggestion: How about moving our [trello board](https://trello.com/b/75kn8xCu/elixir-school-translation-board) to new, fancy, shiny, and full-integrated GitHub Projects?

**Comment by flavono123** [comment]
Thanks for good lessons in advance

All Korean translations are done? 
If remained, I'd strongly like to do that!

**Comment by doomspork** [comment]
Welcome @flavono123!!  @elixirschool/korean any lessons need updates?

**Comment by devleoper** [comment]
Hello @flavono123! Thanks for your participation. :tada:

Since the basic translation is done but as far as I remember there are some refinements and [lesson that is not translated yet](https://elixirschool.com/en/lessons/libraries/benchee/). You can find out those by filtering out [translation issues](https://github.com/elixirschool/elixirschool/issues?q=is%3Aopen+is%3Aissue+label%3Atranslation). Feel free to suggest pull requests if you found some unnatural/awkward translated words, or some words that could be better reading.

**Comment by flavono123** [comment]
@devleoper Thanks for help! I will look there up!

**Comment by eksperimental** [comment]
Should we close this issue since all tasks have been completed?
