### ISSUE TITLE
Create open collective for sponsors?

### ISSUE THREAD

**Issue by ryan-senn** [elixirschool/elixirschool#2158]
Hi,
Not sure if this is something you would consider, but I love elixir school, it really helped me get started with elixir. A lot of projects accept open collective sponsorships, and often have a sponsors section in the sidebar or at the bottom with a link to the sponsor. I would be happy to contribute $10-$20 a month to support the hard work put into this great resource.

**Comment by doomspork** [comment]
Hi @ryan-senn! Thank you so much for the kind words and bringing up such an important topic. Truth be told I've been on the fence about how to accept donations for a _long_ time, going so far as to write an almost complete Patreon clone in Elixir for Elixir School. Ultimately I've always held off because of concern for how funds might impact both the community's perception of the project and the community's willingness to get involved. 

I'd love to be able to given back to the community even more, and to those who've helped make this resource so amazing, but I'm not entirely sure how to do that fairly. What do you think? I'm open to any and all suggestions :grin:

**Comment by ryan-senn** [comment]
I can't speak for everyone, but personally I look at it positively. I think what makes projects such a elixirschool thrive is the community and support we receive from one another. I've seen many great open source projects abandoned over the years, and IMO this is exactly where open collective shines as it gives creators incentives to keep up the great work.

> going so far as to write an almost complete Patreon clone in Elixir for Elixir School. Ultimately I've always held off

I think you just perfectly described what I was trying to say! If my (and possibly others) humble sponsorship can make this happen, I'm all for it! I would absolutely love to see a patreon clone in elixir! I think it's a little bit like a positive feedback loop really, I love what you created so I give some love back, and in turn you create more things that I love!

Maybe it would be worthy of asking in elixir forums? It's unlikely that this issue will receive much exposure.

**Comment by doomspork** [comment]
I am going to work on setting up a GitHub Sponsors for this to coincide with the launch of the new site.
