### ISSUE TITLE
[New Content] Internationalization

### ISSUE THREAD

**Issue by dbernheisel** [elixirschool/elixirschool#2269]
Developers sometimes need to develop apps that lend itself to translation. Not only written words, but units, calendars, money, and encodings. 

We could add lessons for these facets:

- [ ] Gettext
  - [ ] Usage in Elixir
  - [ ] Translation of POs
- [ ] Cldr Library (h/t @kipcole9)
  - [ ] Calendars, dates, and times
  - [ ] Currency
  - [ ] Units, etc.
- [ ] Text encoding
  - [ ] Built-in (Erlang) translation between UTFs and Latin1
  - [ ] Other encodings

**Comment by doomspork** [comment]
This is a good lesson to include with the new batch we'll be doing for the new site roll out. For now I'd like to keep this focused on just `gettext` and avoid referencing additional libraries. This has been a problem in other parts of our content due to library APIs shifting.

I'll consolidate this issue into a larger one outlining the aforementioned batch 👍
