### ISSUE TITLE
[Suggestion] Add Example Project implementing what was learned per chapter.

### ISSUE THREAD

**Issue by cubuzz** [elixirschool/elixirschool#2295]
This is something that I'm currently working on, but this should allow people like me that learn from example better than from documentation and standalone examples to grasp the idea of the lang easier. I'm creating a fork in which I will implement this in the english version.

**Comment by Snackomat** [comment]
You can assign this to me if you want to, I'm currently working on implementing this. You visit my fork if you wish to see my progress.

**Comment by wkulikowski** [comment]
Hi @Snackomat are you still working on this? I came here to post exactly the same suggestion and would like to work on it as well.

I am a Python dev by trade, so if I can even give some insight on the projects as an Elixir newcomer

**Comment by doomspork** [comment]
@wkulikowski I'd love to hear your thoughts! I've added a few examples in some lessons but the trend never caught on so I gave it pause.  I also started this repo of projects which I had opened to tie in with the lessons but interest in that approach was lacking: https://github.com/elixirschool/homework

I wholly agree that examples and "homework" would really help drive home the point of the content. Suggestions on how best to achieve I'd love to hear!

**Comment by wkulikowski** [comment]
Oh that's cool! Tbh once I finished `basics` section I was disappointed that there is no easy / guided way to put the skills to use.
The perfect approach for me would be a section `homework` with a set of tasks and sample solutions I could go through. These tasks would be categorised by `algorithms`, `web server`, `databases` etc.

I like the homework project! Especially the spread of categories, but I think they should be accessible from the frontend and have solutions with "elegant" code.

If you like the concept I would love to work on it. `contributing.md` doesn't specify how should I go about it, so I would need a little guidance. But aside of that, I feel comfortable in Jekyll and can do some conceptual work on it. Let me know if any of this is possible

**Comment by doomspork** [comment]
@wkulikowski I'd love your help! This is truly a community project. For the most part our guides have focused on translators (the majority of contributors). Folks who've wanted to do more than that have typically opened issues like @Snackomat did for discussion, from there we figure out the plan forward.

The Homework repo probably needs a radical overhaul now that it's gone untouched for so long; we don't even need to consider it in this. A new homework section per lesson would be _spectacular_. Couple of questions:

1. Can we make a plan for all lessons and roll this out incrementally? I think this could be a lot of work potentially.
2. Is there a way we can allow people to submit their solution somewhere for feedback (volunteer based)

**Comment by wkulikowski** [comment]
1. I agree, incremental approach will be the best. We will need more feedback than just ideas of 3 people 😃
2. What about taking advantage of GH Pull Requests? For example, if I am doing a project `fizz buzz`, I could do a PR like this one: https://github.com/elixirschool/homework/pull/10 and get comments from approved volunteers.

**Comment by wkulikowski** [comment]
I could realistically devote ~10h a week to this project (but from obvious reasons I will have trouble working on the solutions)

At first we could run a section "homework" under chosen beta articles (mix of basic/advanced/ecto) as the MVP. They could read along the lines "fork this project, do tasks from the instruction, run test suite. Compare with our solution in other folder or open PR so some volunteer will rate it"

**Comment by wkulikowski** [comment]
Hi @doomspork are we still considering this?

**Comment by doomspork** [comment]
Howdy @wkulikowski! Yes very much, I've been swamped lately with work so my time for open source has been very minimal. Apologizes for delays here.

I would love to hear what some of the other contributors thing to this approach as well. The success of this project (like any of our others) is definitely going to be depend on having a group of motivated contributors.

@SophieDeBenedetto any thoughts here? Given your teaching background and everything else you've done you have a lot of experience to speak from.

@gemantzu I know you've been doing some mentoring and using our materials. What do you think about this? 

@elixirschool/developers any concerns?

**Comment by SophieDeBenedetto** [comment]
Hello @wkulikowski! I also apologize for being a bit out of the loop--it's been a very busy time but I am so excited about the ideas you're putting forward here! 

Your suggestion here:

> fork this project, do tasks from the instruction, run test suite. Compare with our solution in other folder or open PR so some volunteer will rate it

Seems like an excellent place to start. When I was teaching software engineering at a bootcamp, this is more or less how we structured all of our lessons. The format was:

* Read this lesson 
* Fork a repo that has some instructions and some tests that you need to get passing 
* Submit your work via PR for review/to see the solution/get peer feedback

In my experience, hands-on programming is the best way to learn and I'm really excited about the idea of incorporating it into Elixir School. 

I am definitely interested in and available to support the work of developing such "homework assignments" if you want to take the lead @wkulikowski. By "take the lead" I mean contribute the homework assignments and I can help review them, add solutions, get them added to `github.com/elixirschool` and try to identify other Elixir School contributors to join in this effort. 

I think a good place to start would be to identify, as you suggested, a handful of "beta lessons" to provide homework for. 

I think our next steps are:

* Develop and finalize a list of "beta lessons" to make homework assignments for. 
  * My proposal is to start with 5 lessons, one from each of the main sections (Basics, Advanced, Ecto, Specifics, Libraries)
* Decide on how we will develop and deploy these homework assignments
  * My proposal is to create a new lesson page for each given homework assignment on elixirschool.com, in Ecto. Essentially treat a given homework assignment as a new lesson and add it to the elixir school repo following [these contributing guidelines](https://github.com/elixirschool/elixirschool/blob/master/CONTRIBUTING.md#adding-a-new-lesson). The content of the "homework lesson" should be standardized and brief--a paragraph introducing the assignment and linking to a the assignment's repo under the `elixirschool` org. That repo will contain the detailed instructions in the README as well as a solution branch. 

Once we launch our first 5 or so homework assignments, we can promote them and use them to generate more interest from students and potential contributors to grow this effort. 

I do want to mention a few concerns and get some thoughts on them too--

* Translations: How do we engage our contributors to provide translations for not just homework assignment "lessons" in elixirschool.com but also for the homework repos themselves? 
* Keeping up momentum: Adding homework assignments for every lesson is not realistic I think. How do we set incremental goals for new homework assignments that we can achieve and retain a reasonable level of commitment from contributors? I think we may want to get a participation commitment from one or two more contributors before moving forward. 

@doomspork @wkulikowski what do you guys think? If we'd like to move forward, let's: 
* Identify one or two more contributors to take part
* Continue to use this issue to propose and finalize the list of "beta" lessons
* Continue to use this issue to finalize the development/deployment approach.

**Comment by wkulikowski** [comment]
Hi @doomspork and @SophieDeBenedetto , great to hear back from you! This is obviously a challenging time and I probably wouldn't get much done in the past week either.

Please find my answers below.

### Further work and "taking the lead"
I agree that the project is rather ambitious and will require some motivated collaborators. Guess we can start with one 😄Feeling ok with taking the first batch of work on myself

With respect to @SophieDeBenedetto `next steps` proposal:
> My proposal to start with 5 lessons, one from each of the main sections (Basics, Advanced, Ecto, Specifics, Libraries)
1. **I can finish this by the end of the next week**. One of my time demanding projects finishes on Monday (15.06.2020) and I'll be able to focus on delivering these lessons right after.
2. While first 3 sections are achievable, I am an Elixir beginner myself -- probably will have hard time delivering lessons on `Specifics` and `Libraries`. Shall we pick an additional 2 topics from first 3 sections? Other ideas?

>My proposal is to create a new lesson page for each given homework assignment on elixirschool.com, in Ecto. Essentially treat a given homework assignment as a new lesson and add it to the elixir school repo following these contributing guidelines. The content of the "homework lesson" should be standardized and brief--a paragraph introducing the assignment and linking to a the assignment's repo under the elixirschool org. That repo will contain the detailed instructions in the README as well as a solution branch.

**I like this approach** because it's lean and we don't loose anything in case when the homeworks don't take off. *My proposal* would be to go with this one, but reconsider implementing a new page format for *homeworks* if they become popular -- afterall putting them as *lessons* is a little bit of a hack.

### Addressing the concerns
> Translations: How do we engage our contributors to provide translations for not just homework assignment "lessons" in elixirschool.com but also for the homework repos themselves?

Thanks for putting this so upfront, I didn't realise the importance of translations in Elixir School till now. However, I wouldn't consider that to be a problem *now* -- let's build some first homeworks and if they stick we can always figure out the translation process later. In the extreme case we could automate the changes, so the contents of the "homeworks" repo are deployed from the main repo. Honestly don't know the answer here and I feel like I don't know the complexity of this problem enough.

> Keeping up momentum: Adding homework assignments for every lesson is not realistic I think. How do we set incremental goals for new homework assignments that we can achieve and retain a reasonable level of commitment from contributors? I think we may want to get a participation commitment from one or two more contributors before moving forward.

My stand here doesn't really change, as I don't know the elixir school community, nor the driving factors for the lesson development. However,
1. We could work on N homeworks at the time and launch them in bigger "homework releases".
2. The assumption here would be that we never expect to have 100% lesson/homework coverage, but there will be ready homeworks for *some* lessons and always N upcoming homeworks


### Moving forward:
🚀Identify one or two more contributors to take part -- Who wants to be my partner in crime? 😄 
✅Continue to use this issue to propose and finalize the list of "beta" lessons
✅Continue to use this issue to finalize the development/deployment approach.

### Personal summary
Thanks for the replies! They certainly made my day better. Action points:
1. I'll prepare the example homeworks by the end of next week.
2. If nothing new pops up here -- I'll deploy them as lessons, together with come simple contributing guidelines
3. @SophieDeBenedetto will you please review the content for me? Please keep in mind that I am not proficient in Elixir yet

**Comment by carlogilmar** [comment]
Hi everyone! I'm reading all your ideas, and are so great! Right now I have to teach Elixir from zero and I was reading the Elixir School guides and looking for how to create a good learning experience. 

If you need some contributors, I'll be happy to help to build this, and help with other things (translation to spanish, graphic recordings, etc)

**Comment by SophieDeBenedetto** [comment]
Hi @carlogilmar! So great that you're interesting in contributing to this "homework project"! @wkulikowski is there a way that @carlogilmar  or I could plug in right away? Or is it better to wait until you have something for us to review?

**Comment by wkulikowski** [comment]
As I mentioned before, yesterday I finished a side project, and today I am starting to work on this one — so we start with a blank canvas. I was thinking about preparing a homework on `pattern matching` and `OTP Concurrency`.

When I'm ready I will submit my ideas for @SophieDeBenedetto review, I think you can do the same! Let's just not pick overlapping lessons :)

After the review we can work out a proper format and them implement the first batch of lessons

**Comment by SophieDeBenedetto** [comment]
Thanks for the update @wkulikowski! I agree we should work out a consistent format for each homework lesson. If you have an outline or format in-mind, feel free to share here and we can all follow that format. Or (and I think this is what you're saying 😄 ) we can wait until you submit a first draft and then use the review of that content to agree on the format. 

Congrats on finishing up your side project 🎉

**Comment by wkulikowski** [comment]
Just fyi, I am still working on it -- have the pattern matching project half-baked and learning about GenServer now. It is much harder with simultaneously learning & crafting a project, but we will get there!
