### ISSUE TITLE
Worked on an Elixir School PR and now my localhost:4000 is always defaulting to localhost:4000/en with Elixir School content

### ISSUE THREAD

**Issue by ItzaMi** [elixirschool/elixirschool#2539]
The title is quite long but I'm wondering if this has happened to anyone before since before working on `elixir school` everything was going ok.  
On Chrome I was able to fix this by clearing the `Cache Storage` but when I do changes to my Phoenix project my `localhost:4000` updates to the regular phoenix template page and I have to `hard refresh` the page to see my changes.  
  
On Firefox I'm not even able to get to `localhost:4000` because I get redirected to `localhost:4000/en` and that page has `Elixir School` content. Clearing the cache isn't working for me there and I was wondering if anyone had this problem before and if you could help me with it

**Comment by doomspork** [comment]
@ItzaMi I'm hoping this goes away with the new site we're building as this I believe is tied to the Jekyll plugin we use.

Does the issue happen in Firefox even when you use an incognito browser? I'm pretty sure the issue is the 301 that Jekyll uses which tells the browser this is a permanent redirect.

**Comment by ItzaMi** [comment]
@doomspork , I have since then removed my local instance of `elixir school` so I'm unsure if the problem got solved / persisted, sorry
