### ISSUE TITLE
Add exercise for Enum Lesson

### ISSUE THREAD

**Issue by beeetooo** [elixirschool/elixirschool#399]
## Exercise for Enum Lesson - Count the repetitions of a character in a string

Given a string X, return an array with the number of repetitions of the characters inside the string.
For example:
Input: `character`
Output:

``` js
{
  c: 2,
  a: 2,
  h: 1,
  r: 2,
  e: 1,
  t: 1
}
```

Any thoughts @doomspork @pjhampton?

**Comment by setzer777** [comment]
I don't know if we should be building complex exercises or simple ones? Maybe we can include one of each difficulty?

**Comment by doomspork** [comment]
I think 1-2 simple ones and a more difficult one, if applicable.

**Comment by setzer777** [comment]
I would rather prefer to have one easy and one complex, otherwise we would be saturating the lessons with exercises, which I think is not the best idea, but let's open a debate for this.

**Comment by doomspork** [comment]
Truthfully I think the lesson will dictate the exercises.  More advanced lesson will likely only have a single, more complex example.  Basics and fundamentals make sense having more than one exercise.

**Comment by setzer777** [comment]
Yeah, I think you are right 👍 So, let me propose this:
1. *For basic lessons*: From one to two exercises, an easy and a complex.
2. *For advanced lessons*: One complex exercise.

Are we tuned? c:

**Comment by nscyclone** [comment]
Well, I think that just posting those exercises at the bottom of each lesson is not the best and modern way to interact with user. Maybe we should look into adding our custom Elixir course at some programming education services (e.g. 'codecademy')? There is José's [course](https://www.pluralsight.com/courses/meet-elixir) at pluralsight.com but it isn't free.
Or if we feel ourselves strong enough we could create our own that kind of project especially for Elixir exercises but it may look like reinventing a wheel.

**Comment by doomspork** [comment]
Sorry it's taken me so long to get back to this particular topic!

@nscyclone I do agree with you that listing exercises at the bottom of each lesson isn't a very modern way of doing things, personally I'm not a huge fan of it either.  That said, I have heard from a lot of folks that they'd like some exercises to go along with the content.  I think appending the exercises to the bottom of lessons is a suitable stop gap until we figure out something better.

In regards to making things better, I've been looking into what it might take to re-build Elixir School as an open-source Phoenix app that could serve as a basis for other open-schools.  As part of that I'd like to look at how to provide more interactive exercises, similar to what we see on Codecademy or [Elixir  Playground](http://elixirplayground.com/).  The move to Phoenix might also help improve translations by way of gettext.  

It would be a pretty significant undertaking so I want to take the time to plan it out, document the tasks in GitHub, and make it a project that gets people to engage with Elixir School, Elixir, and Phoenix, all while giving back to open source.  Thoughts?  Questions?  Concerns?

**Comment by nscyclone** [comment]
@doomspork, I can't tell anything concrete for now but I think we could get some feedback from the community before we start. I mean, for example, we could add a temporary [form](https://formspree.io/) at the footer with a small description like: "The great growing community inspired us to make an open-source IT learning project. Feel free to share your thoughts, suggestions and wishes with us!". When a user is just a click away from sending his opinion, there is more chance that he will contribute. And since the community is really great and growing the impact might be very impressive.

**Comment by doomspork** [comment]
@nscyclone I think reaching out to the community would be a great idea, we can also distribute a survey via Twitter.

**Comment by nscyclone** [comment]
@doomspork, I've spent some time to write a long post and finally decided to discard it.
Actually, Twitter is good but I am not sure that its polls could be useful for this case at the starting stage &mdash; we don't yet know what to ask and what could people vote for. For now, we could stick a tweet telling that we're requesting some feedback (maybe a special hashtag could be used for the easier sorting and stuff). We would have to manage it manually, ignoring the junk and retweeting the related messages. Likes would tell us which ones are really worthy and in the end we could make some polls to finally decide what to bring to life.
I would highly recommend to embed both the sticked post and the latest messages somewhere on the site because our Twitter audience is much smaller than the site users.

**Comment by doomspork** [comment]
I was assuming we'd put the survey or form elsewhere and use Twitter to assist in distributing a link to it.

**Comment by nscyclone** [comment]
@doomspork, sorry, I misunderstood that. Anyway sharing the received suggestions via Twitter to see the actual support for each one is a viable idea. 
So what, in your opinion, is the best way to ask for feedback?

**Comment by setzer777** [comment]
I think twitter polls could be really great c: I agree in everything you said haha

**Comment by setzer777** [comment]
Why don't we start today? Let's just ask for feedback in Twitter and see what happens 👍 :shipit:

**Comment by doomspork** [comment]
Done @setzer777 — https://twitter.com/elixirschool/status/745405806040911872

**Comment by holsky** [comment]
As a beginner I would also really appreciate some exercises in the lessons. I agree that there are more modern ways than exercises at the bottom of lessons, but the cost-value ratio is pretty high. Did you make any decision in this regard yet?

**Comment by doomspork** [comment]
Closing this as the conversation has resumed here #1310
