### ISSUE TITLE
Full fledge example projects

### ISSUE THREAD

**Issue by doomspork** [elixirschool/elixirschool#768]
I'd like to open up discussions about a new section or sub-site to Elixir School for full-fledged projects.  This would be something different from individual lesson exercises.  I envision these projects spanning multiple lessons and serving as examples for applying the knowledge and further familiarizing one's self with Elixir development.

This has been of particular interest to @ybur-yug and is something I too have a lot of interest in.  I'd like to use this issue as a place for contributors and others to voice their thoughts on how we could proceed with this initiative and not negatively impact the quality of the site or the workload of translators.

Care to share your thoughts @brain-geek / @nscyclone / @pjhampton / @pragmaticivan / @devleoper and others?

**Comment by doomspork** [comment]
@ybur-yug could you give everyone the gist of what you had in mind?  I know this is something you've really wanted to get started for awhile now.

**Comment by pjhampton** [comment]
I like the idea!
What is the current stats looking like from the google analytics @doomspork? What are you more popular lessons?

**Comment by doomspork** [comment]
@pjhampton I don't think I've ever dug into the analytics to look at that, great idea!  @ybur-yug had a suggestion for a full fledge GenStage example application, that's the hottness right now so might be a great start.

The trick, in my opinion, will be coming up with real world problems that relatable and easy to follow along with.  It's easy to come up with contrived examples but that doesn't help anyone in my opinion.

**Comment by pragmaticivan** [comment]
I like the idea, but for this case I would suggest more images, illustration and a better explanation visually about what's going on. Not just code and text.

**Comment by doomspork** [comment]
Agreed @pragmaticivan!  I think there needs to be more content, these projects should be in-depth.

**Comment by ybur-yug** [comment]
@pragmaticivan what kind of example imagery are you thinking of?

[this](https://github.com/ybur-yug/genstage_tutorial) is the tutorial I had written up that just ended up too meaty. I mean I guess to expand you could incorporate it into an umbrella and have some imagery of the observer and the flow of demand from producer --> consumer etc.

I'm not as useful on those notes because I prefer things to be dense. Code and text only etc. However obviously if it works well for others and this is learning content, I best add some, but I'm not sure what exactly the best strategy/areas would be for it. Feel free to leave a comment on the latest commit on some lines that you think imagery could be used.

That draft is still super-rough but I think it gets across the idea of building something nontrivial though it could go furhter into the internals.

I also have been working on something similar for a large umbrella project that I can think of some more imagery etc examples for.

I also wonder if these would be better off on a subdomain since they could easily get big and take multiple days to DIY. Maybe something like `university.elixirschool.com` or `labs.elixirschool.com` or anything along those lines. We could feel out what the community likes as we release content and react from there.

**Comment by gemantzu** [comment]
This would be so awesome I cannot even measure how much. We should add full fledged projects about everything we talk in here. This would make the very definition of the term "school" more complete (we would still need exercises for it to be 100%)
